### ISSUE TITLE
gulp-declare 是干什么用的

### ISSUE THREAD

**Issue by wuyanwen** [nimojs/gulp-demo#2]
gulp-declare 是干什么用的，没有相关的中文介绍。

**Comment by nimoc** [comment]
1. 找到 github https://github.com/lazd/gulp-declare
2. 用有道翻译和看示例代码
3. 自己按照示例跑一遍
4. github 搜索代码 https://github.com/search?q=gulp-declare+&type=Code&utf8=%E2%9C%93 看看别人是怎么用的

按照这个步骤来，基本上各种 gulp 组件都能知道是干啥的
